title: Nocnitsa
description: >-
  black magic code

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Minima settings
google_analytics: G-MHYL9TY0PV
minima:
  skin: auto
