title: Nocnitsa
email: gabrielhk3@gmail.com
description: >-
  black magic code
baseurl: ""
url: ""
twitter_username: gabhk3
github_username: th3rius
google_analytics: G-MHYL9TY0PV
minima:
  skin: auto

# Build settings
theme: minima
plugins:
  - jekyll-feed
