title: Nocnitsa
tagline: Black magic code
description: >-
  Ancient magic chanted in form of lines of codes.
  I also like cats.
url: http://nocnitsa.com
author:
  name: Gabriel de Oliveira
  email: "gabrielhk3@gmail.com"
show_excerpts: true
disqus:
  shortname: blackmagiccode

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Minima settings
google_analytics: G-MHYL9TY0PV
google_adsense: ca-pub-5238376130252175
minima:
  skin: auto
  social_links:
    - title: th3rius at GitHub
      icon: github
      url: "https://github.com/th3rius"
    - title: Gabriel de Oliveira at LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/gabrielhk3"
